### ISSUE TITLE
perf: investigate dynamic level-multiplier

### ISSUE THREAD

**Issue by petermattis** [petermattis/pebble#135]
https://github.com/petermattis/pebble/pull/134 removed the dynamic base-level-size and the dynamic level-multiplier. The latter was only turned on in special circumstances:

	if l0Size > baseLevelSize &&	
		(l0Size > opts.L1MaxBytes ||	
			(len(v.files)/2) >= opts.L0CompactionThreshold) {	
		// We adjust the base level according to actual L0 size, and adjust the	
		// level multiplier accordingly, when:	
		//	
		//   1. the L0 size is larger than level size base, or	
		//   2. number of L0 files reaches twice the L0->L1 compaction threshold	
		//	
		// We don't do this otherwise to keep the LSM-tree structure stable unless	
		// the L0 compaction is backlogged.	
		baseLevelSize = l0Size	
		if p.baseLevel == numLevels-1 {	
			levelMultiplier = 1.0	
		} else {	
			levelMultiplier = math.Pow(
				float64(maxLevelSize)/float64(baseLevelSize),	
				1.0/float64(numLevels-p.baseLevel-1))	
		}	
	}

The dynamic base-level-size was clearly problematic as it could lead to an excessively large base-level-size if L0 was getting backed up. The above heuristic is less obviously problematic. The original LSM paper (http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.44.2782&rep=rep1&type=pdf) proved that for a particular bottom-level size and base-level size there is a level-multiplier which minimizes write-amp. That is what the above code is computing. It isn't obvious to me if this result holds as the database size is changing. It isn't obvious to me that the calculation above is correct as it isn't considering the bottom-level size, but the size of the largest level.

Cc @ajkr

**Comment by petermattis** [comment]
One funkiness about the dynamic adjustment of `levelMultiplier` above is that we're dynamically adjusting the number of levels prior to this adjustment, and the selection of the number of levels is using the default `levelMultiplier` of `10`. That is, we use a `levelMultiplier` of `10` to determine the number of levels, then use that number of levels to determine what `levelMultiplier` will optimize write-amplification. Can't we get better write-amplification if we tune the number of levels to reduce write-amplification first?

**Comment by ajkr** [comment]
From the perspective of write-amp alone I think more levels always gets better write-amp. For example we could always compact L0 into a fresh empty level. But that'd cause read-amp and space-amp to suffer. So I think the question we need to answer is, how do we balance the write-amp benefit we get from having more levels with the space/read penalties?

The way RocksDB does it is using `max_bytes_for_level_multiplier` to decide how many levels, then based on that pick a smoothed level multiplier. I imagine something more adaptive is possible, but maybe that's a decent starting point. At least I have some experiments running with that logic (and also replacing largest level size with bottom level size in the compaction scoring formulas). Will post results shortly.

**Comment by ajkr** [comment]
The experiment involves two hours of random writes followed by waiting for all compactions to finish. The random writes are generated by `pebble ycsb` with read-percent 0, concurrency 512, batch size 1, and value size 128.

Explanation of results columns:

- `target-bottom-size`: whether it contains the change to use bottom level size in the compaction scoring formula
- `multiplier-smoothing`: whether the fanout between levels is fixed
- `burst-write-amp`: write-amp during the first phase of the experiment, where writes are happening as fast as possible
- `total-write-amp`: write-amp over both phases of the experiment. The second phase is only doing compaction until all the levels have score <= 1.0.

target-bottom-size | multiplier-smoothing | ops/sec | burst-write-amp | total-write-amp
-- | -- | -- | -- | --
0 | 0 | 42106.5 | 10.3 | 12.6
1 | 0 | 39367.7 | 10.2 | 12.2
1 | 1 | 46139.4 | 10.9 | 13.1

Observations:

- In retrospect I should've fixed the number of operations rather than fixing the experiment time. The way I did it, the faster one will end up with a larger LSM, so larger write-amp is expected. So the write-amp columns do not give fair comparisons.
- I expected an efficiency (total-write-amp) improvement with this change, not so much a performance (ops/sec) improvement. So the results surprise me.
- Another thing I wanted to measure was peak space-amp. But since it's writing all new keys there is no space-amp. Perhaps an experiment where we start with an existing large DB and do a burst of overwrites on it would be useful (although I am not sure how well this reflects Cockroach's use case).

**Comment by petermattis** [comment]
> From the perspective of write-amp alone I think more levels always gets better write-amp. For example we could always compact L0 into a fresh empty level. But that'd cause read-amp and space-amp to suffer. So I think the question we need to answer is, how do we balance the write-amp benefit we get from having more levels with the space/read penalties?

The space-amp from more levels should be fairly minimal. The read-amp is a better question, but I think if we limit it to the default 7 we'd be ok. I'm imagining that we could do something like: determine number of levels using `level-multiplier=2`, capping the number of levels to 6 (L1 through L6). Then, determine the optimal level-multiplier for that number of levels.

> `target-bottom-size`: whether it contains the change to use bottom level size in the compaction scoring formula

Can you elaborate on the thinking behind this heuristic? In my recent experiments, the bottom-size level can be significantly smaller than the largest level due to compaction starvation. I'm not sure if this heuristic is bad, but I'm not quite sure what it is accomplishing.

**Comment by ajkr** [comment]
Here's the updated results for fixed number of keys (300M) rather than fixed amount of time (2h). Again, the ops/sec is better but the total-write-amp is not really affected.

target-bottom-size | multiplier-smoothing | ops/sec | burst write-amp | overall write-amp
-- | -- | -- | -- | --
0 | 0 | 45757.1 | 10.9 | 13.1
1 | 0 | 43332.9 | 11.3 | 13.2
1 | 1 | 49365.1 | 10.8 | 13.1

**Comment by ajkr** [comment]
> The space-amp from more levels should be fairly minimal. The read-amp is a better question, but I think if we limit it to the default 7 we'd be ok. I'm imagining that we could do something like: determine number of levels using level-multiplier=2, capping the number of levels to 6 (L1 through L6). Then, determine the optimal level-multiplier for that number of levels.

I think the space overhead then is ~50% rather than ~10%. If we can afford that we should change the RocksDB config, too, as its default (`max_bytes_for_level_multiplier=10`) is tuned for super low space overhead at the cost of expensive compactions.

> Can you elaborate on the thinking behind this heuristic? In my recent experiments, the bottom-size level can be significantly smaller than the largest level due to compaction starvation. I'm not sure if this heuristic is bad, but I'm not quite sure what it is accomplishing.

I don't know either. It makes the LSM a strange shape, like you said, by starving lower-level compactions. It seems to have beneficial effects on write bursts comparing the `burst write-amp` values of `target-bottom-size=0,multiplier-smoothing=0` vs. `target-bottom-size=1,multiplier-smoothing=0`. I guess it makes sense since it's letting upper-level compactions happen faster by blocking lower-level ones.

**Comment by petermattis** [comment]
> I think the space overhead then is ~50% rather than ~10%. If we can afford that we should change the RocksDB config, too, as its default (max_bytes_for_level_multiplier=10) is tuned for super low space overhead at the cost of expensive compactions.

The space overhead would only be 50% when the database size is small. As the database grows the `level-multiplier` would grow, reducing space-amplification.

I was thinking about this more on my drive today, and I feel that there is something fundamentally odd about using either max-level-size or bottommost-level-size in the calculation here. Both cause the level-multiplier to fluctuate rapidly as compactions occur. Seems to me that we should be looking at the total amount of data across all levels, and then deciding on the height and shape of the tree we want from that. http://smalldatum.blogspot.com/2018/12/lsm-math-how-many-levels-minimizes.html touches on this same idea.

**Comment by petermattis** [comment]
@ajkr Do you think it is worthwhile keeping this open now that #150 is merged?

**Comment by ajkr** [comment]
I think this is mostly resolved. We can keep in mind that using the fixed divisor `10` when calculating the number of levels may be worth revisiting.
