### ISSUE TITLE
db: support changing {Lower,Upper}Bound on an iterator

### ISSUE THREAD

**Issue by petermattis** [petermattis/pebble#143]
CockroachDB likes to specify tight lower and upper bounds when iterating with an iterator, but in order to maintain snapshot semantics, it wants to reuse the same iterator across multiple operations within the same batch of operations. It accomplishes this with RocksDB by abusing the iterator API. `ReadOptions::iterate_{lower,upper}_bound` are configured to point to valid slices, and CockroachDB changes the contents of those slices before calls to `Seek`.

A better API to accomplish this would be to provide an `Iterator.SetBounds` or `Iterator.SetOptions` method. This would likely necessitate an `internalIterator.SetBounds` method. None of this seems particularly complex. I think the semantics of `Iterator.SetBounds` should be that it doesn't change the current state of the iterator. If the iterator was valid before the call it will remain valid after the `SetBounds` call and positioned at the same entry. If the iterator was invalid before the call it will remain invalid after the `SetBounds` call. The new bounds only apply to subsequent positioning operations (`Seek{GE,LT}`, `First`, `Last`, `Next`, `Prev`). If these semantics are burdensome, we could have `SetBounds` always invalidate the iterator.

Cc @ajkr, @Ryanfsdf

**Comment by petermattis** [comment]
@Ryanfsdf this seems like a natural follow-on to your work on prefix iterators.

**Comment by Ryanfsdf** [comment]
There are some edge cases which come up if we allow `Next` and `Prev` to be called immediately after calling `SetBounds`.

For example:
```
define
a.SET.1:a
b.SET.1:b
c.SET.1:c
----

iter seq=2
seek-ge c
set-bounds upper=b
prev // b
prev // a
next // .
----
c:c
b:b
a:a
.
```
This may be unexpected since calling `prev` followed by `next` should return the iterator to a valid position, but it does not. The first call to `prev` puts the iterator in an invalid position, but it is reported as valid because calls to `Prev` do not check the upper bound. 

This problem arises since `sstable.Iterator.Next` does not check the lower bound, and `sstable.Iterator.Prev` does not check the upper bound. It does not come up if we call `Seek{GE, PrefixGE, LT}`, `First`, or `Last` before calling `Next` and `Prev` because `pebble.Iterator` adjusts the key to fit inside `lower,upper{bound}` in its call to `Seek{GE, PrefixGE, LT}`, `First`, and `Last`, before calling its `internalIterator`.

I think the `SetBounds` contract should include a condition that `Next` and `Prev` should not be subsequently called until the iterator has been repositioned with `Seek{GE, PrefixGE, LT}`, `First`, or `Last`. This is essentially the same as always invalidating the iterator.

Another option would be to check if the iterator is positioned within `Lower,Upper{Bound}` in the call to `SetBounds` and return an error if the bounds are invalid.

I'm in favor of the first approach. Please let me know if you have any thoughts on this!

**Comment by petermattis** [comment]
> I think the SetBounds contract should include a condition that Next and Prev should not be subsequently called until the iterator has been repositioned with Seek{GE, PrefixGE, LT}, First, or Last. This is essentially the same as always invalidating the iterator.

This sounds good to me. I'd phrase this as the result of `Next` and `Prev` are *undefined* after a call to `SetBounds` until the iterator has been repositioned with a call to `Seek{GE,PrefixGE,LT}`, `First`, or `Last`.

Another possibility is to make `SetBounds` explicitly invalidate the iterator as if it had newly created. I think this could be done by setting `Iterator.valid = false` and `Iterator.iter{Key,Value} = {nil,nil}`. Probably worthwhile to clear `Iterator.prefix` as well.
